---
- hosts: all
  roles:
      - role: sqlserver
        when: role == 'sql'
        buildPath: "{{ buildpath }}"
        bakfilePath: "{{ bakpath }}"
        databaseName: "{{ dbname }}"

      - role: webserver
        when: role == 'web'
        buildPath: "{{ buildpath }}"
        databaseName: "{{ dbname }}"
        primarysqlinstance: "{{ sqlinstancename }}"
        websitename: "{{ iiswebsite }}"
