---
- hosts: all
  connection: local
  gather_facts: False

  vars_prompt:
    - name: "user"
      prompt: "Enter vcenter username"
      private: no
    - name: "pass"
      prompt: "Enter vcenter password"
      private: yes

  roles:
      - role: provision-iso
        when: "role == 'web'"
        vcenter_user: "{{ user }}"
        vcenter_pass: "{{ pass }}"
        num_disks: '2'
        disk1: '20'
        disk2: '40'
        datastore: 'SC1_VNX5600_TFSAUTO_03'
        network: 'SERVER_VLAN_122'
        memory: '2048'
        cpucount: '2'
        osid: 'windows8Server64Guest'

      - role: provision-iso
        when: "role == 'sql'"
        vcenter_user: "{{ user }}"
        vcenter_pass: "{{ pass }}"
        num_disks: '4'
        disk1: '20'
        disk2: '40'
        disk3: '40'
        disk4: '40'
        datastore: 'SC1_VNX5600_TFSAUTO_03'
        network: 'SERVER_VLAN_122'
        memory: '4096'
        cpucount: '4'
        osid: 'windows8Server64Guest'



