---
    - when: ("{{ num_disks }}" == '1')
      vsphere_guest:
        vcenter_hostname: "{{ vcenterhostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        state: present
        vm_hw_version: vmx-08
        vm_extra_config:
          notes: "{{ notes }}"
          folder: "Testboxes"
        vm_disk:
          disk1:
            size_gb: "{{ disk1 }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: e1000e
            network: "{{ network }}"
            network_type: dvs
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: windows8Server64Guest
          scsi: lsi_sas
          vm_cdrom:
            type: "iso"
            iso_path: "{{ isopath }}"
        esxi:
          datacenter: "Enterprise Test Lab"
          hostname: "{{ esxhostname }}"
    - when: ("{{ num_disks }}" == '2')
      vsphere_guest:
        vcenter_hostname: "{{ vcenterhostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        state: present
        vm_hw_version: vmx-08
        vm_extra_config:
          notes: "{{ notes }}"
          folder: "Testboxes"
        vm_disk:
          disk1:
            size_gb: "{{ disk1 }}"
            type: thin
            datastore: "{{ datastore }}"
          disk2:
            size_gb: "{{ disk2 }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: e1000e
            network: "{{ network }}"
            network_type: dvs
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: windows8Server64Guest
          scsi: lsi_sas
          vm_cdrom:
            type: "iso"
            iso_path: "{{ isopath }}"
        esxi:
          datacenter: "Enterprise Test Lab"
          hostname: "{{ esxhostname }}"
    - when: ("{{ num_disks }}" == '4')
      vsphere_guest:
        vcenter_hostname: "{{ vcenterhostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        state: present
        vm_hw_version: vmx-08
        vm_extra_config:
          notes: "{{ notes }}"
          folder: "Testboxes"
        vm_disk:
          disk1:
            size_gb: "{{ disk1 }}"
            type: thin
            datastore: "{{ datastore }}"
          disk2:
            size_gb: "{{ disk2 }}"
            type: thin
            datastore: "{{ datastore }}"
          disk3:
            size_gb: "{{ disk3 }}"
            type: thin
            datastore: "{{ datastore }}"
          disk4:
            size_gb: "{{ disk4 }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: e1000e
            network: "{{ network }}"
            network_type: dvs
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: windows8Server64Guest
          scsi: lsi_sas
          vm_cdrom:
            type: "iso"
            iso_path: "{{ isopath }}"
        esxi:
          datacenter: "Enterprise Test Lab"
          hostname: "{{ esxhostname }}"