---
- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  user: local
  sudo: true
  vars:
      RigName: SC1Ans
      VSphereServer: sc10pvcenters01.blackbaud.global
      VSphereUser: <yourusername>
      VSpherePwd: <your password>
      AgtTemplate: AutomationTemplate-GUI2012
      VMCluster: "Automation Lab"
      ResourcePool: "/Resources"
      VMfolder: "Testboxes"
      AgentList:
        - SC1AnsAgt01
        - SC1AnsAgt02

  tasks:
    - name: provision VM agent
      vsphere_guest:
        guest: "{{ RigName }}Agt01"
        vcenter_hostname: "{{ VSphereServer }}"
        username: "{{ VSphereUser }}"
        password: "{{ VSpherePwd }}"
        from_template: yes
        template_src: "{{ AgtTemplate }}"
        cluster: "{{ VMCluster }}"
        resource_pool: "{{ ResourcePool }}"
        vm_folder: "{{ VMfolder }}"
        autologon:
            Autologon: yes
            AutologonUser: "pdnt\\automagic"
            AutologonPwd: "Research6"
