---
- hosts: all
  gather_facts: false
  connection: local

  vars_prompt:
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes

  vars:
    datacenter: "Enterprise Test Lab"
    notes: 'Created by Ansible'

  tasks:
    - when: ("{{ num_disks }}" == '1')
      vsphere_guest:
        vcenter_hostname: sc10pvcsas01.blackbaud.global
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        state: present
        vm_hw_version: vmx-08
        vm_extra_config:
          notes: "{{ notes }}"
          folder: "Testboxes"
        vm_disk:
          disk1:
            size_gb: "{{ disk1 }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: e1000e
            network: "{{ network }}"
            network_type: dvs
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: windows8Server64Guest
          scsi: lsi_sas
          vm_cdrom:
            type: "iso"
            iso_path: "ISO_TFS_AUTO_LAB/Lab ISOs/OS/Windows2012ISO_Core.iso"
        esxi:
          datacenter: "Enterprise Test Lab"
          hostname: sc10pucss07.blackbaud.global
    - when: ("{{ num_disks }}" == '2')
      vsphere_guest:
        vcenter_hostname: sc10pvcsas01.blackbaud.global
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        state: present
        vm_hw_version: vmx-08
        vm_extra_config:
          notes: "{{ notes }}"
          folder: "Testboxes"
        vm_disk:
          disk1:
            size_gb: "{{ disk1 }}"
            type: thin
            datastore: "{{ datastore }}"
          disk2:
            size_gb: "{{ disk2 }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: e1000e
            network: "{{ network }}"
            network_type: dvs
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: windows8Server64Guest
          scsi: lsi_sas
          vm_cdrom:
            type: "iso"
            iso_path: "ISO_TFS_AUTO_LAB/Lab ISOs/OS/Windows2012ISO_Core.iso"
        esxi:
          datacenter: "Enterprise Test Lab"
          hostname: sc10pucss07.blackbaud.global
    - when: ("{{ num_disks }}" == '4')
      vsphere_guest:
        vcenter_hostname: sc10pvcsas01.blackbaud.global
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        state: powered_on
        vm_hw_version: vmx-08
        vm_extra_config:
          notes: "{{ notes }}"
          folder: "Testboxes"
        vm_disk:
          disk1:
            size_gb: "{{ disk1 }}"
            type: thin
            datastore: "{{ datastore }}"
          disk2:
            size_gb: "{{ disk2 }}"
            type: thin
            datastore: "{{ datastore }}"
          disk3:
            size_gb: "{{ disk3 }}"
            type: thin
            datastore: "{{ datastore }}"
          disk4:
            size_gb: "{{ disk4 }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: e1000e
            network: "{{ network }}"
            network_type: dvs
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: windows8Server64Guest
          scsi: lsi_sas
          vm_cdrom:
            type: "iso"
            iso_path: "ISO_TFS_AUTO_LAB/Lab ISOs/OS/Windows2012ISO_Core.iso"
        esxi:
          datacenter: "Enterprise Test Lab"
          hostname: sc10pucss07.blackbaud.global