---
- hosts: 127.0.0.1
  gather_facts: false
  connection: local

  vars_prompt:
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes
    - name: "vm_host"
      prompt: "Enter vm hostname"
      private: no
  vars:
      vcenter_hostname: sc10pvcsas01.blackbaud.global


  tasks:
    - name: gather vm facts
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ vm_host }}"
        vmware_guest_facts: yes
      register: facts
    - debug: var=facts
