---
- name: shell execution
  vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    vm_id: "{{ inventory_hostname }}"
    vm_id_type: vm_name
    vm_username: automagic@PDNT
    vm_password: Research6
    vm_shell: "c:\\windows\\system32\\xcopy.exe"
    vm_shell_cwd: "c:\\windows\\system32"
    vm_shell_args: "\\\\ptlserver9.pdnt.blackbaud.com\\crmpowershell\\machineconfig\\*.ps1 c:\\"
  register: shellout
- debug: var=shellout