---
- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  user: local
  sudo: true
  vars:
      RigName: SC1Ans
      VSphereServer: sc10pvcenters01.blackbaud.global
      VSphereUser: <yourname@blackbaud.com>
      VSpherePwd: <yourpassword>
      AgtTemplate: AutomationTemplate-GUI2012
      VMCluster: "Automation Lab"
      ResourcePool: "/Resources"
      VMfolder: "Testboxes"
      autologondata:
        Autologon: yes
        AutologonUser: "pdnt\\automagic"
        AutologonPwd: "Research6"
  tasks:
    - name: provision VM agent
      vsphere_guest:
        guest: "{{ RigName }}Agt03"
        vcenter_hostname: "{{ VSphereServer }}"
        username: "{{ VSphereUser }}"
        password: "{{ VSpherePwd }}"
        from_template: yes
        template_src: "{{ AgtTemplate }}"
        cluster: "{{ VMCluster }}"
        resource_pool: "{{ ResourcePool }}"
        vm_folder: "{{ VMfolder }}"
        autologon: "{{ autologondata }}"
